### PR TITLE
Add NEI handler

### LINKED ISSUE #10289: let us see the contents of lootbags in survival
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.1.3qf

### Your Proposal

What the title says, allow us to see the content of lootbags in survival. Having to go on creative and having to shift right click on the lootbag to look at its content is pretty annoying, also, a lot of people don't know you can check its content on creative.

### Your Goal

That way we can check if it's worth enchanting them now or upgrading them for the next tier. 

### Your Vision

yes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

### PR DESCRIPTION
**Pull request by miozune**
Close https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10289

### CODE REVIEW

**Comment by miozune** [comment]
Feature freeze is over!

**Comment by Dream-Master** [comment]
yea

**Comment by kuba6000** [comment]
The GUI is so big it goes out of screen on GUI Scale set to Auto, can we do anything about it?
image

**Review by Dream-Master — APPROVED** [review]
we merge this now and @miozune add another pr with some scroll bar or something.

**Pull request merged**
